FROM python:3.6.10

ARG RABBITMQ_DEFAULT_USER
ARG RABBITMQ_DEFAULT_PASS
ARG $RABBITMQ_HOST

RUN groupadd myuser && useradd --create-home --home-dir /apps/worker -g myuser myuser

WORKDIR /apps/worker

RUN pip install redis

ENV CELERY_VERSION 4.0.2

RUN pip install celery=="$CELERY_VERSION"

RUN { \
	echo 'import os'; \
	echo "BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://')"; \
} > celeryconfig.py

ENV CELERY_BROKER_URL amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@$RABBITMQ_HOST
ENV CELERY_ENABLE_UTC = True
ENV CELERY_TIMEZONE = "UTC"

USER myuser
CMD ["celery", "worker"]

#ENTRYPOINT ["/apps/worker/run-celery-worker.sh"]