# pull official base image
FROM python:3.6.10

# set work directory
WORKDIR /apps/worker

#ARG RABBITMQ_DEFAULT_USER
#ARG RABBITMQ_DEFAULT_PASS
#ARG $RABBITMQ_HOST

#RUN groupadd myuser && useradd --create-home --home-dir /apps/worker -g myuser myuser

# install dependencies
RUN pip install --upgrade pip
RUN pip install celery==4.4.2

# create unprivileged user
#RUN adduser --disabled-password --gecos '' myuser

#ADD ./requirements.txt /apps/worker/requirements.txt
#RUN pip install -r requirements.txt

#RUN { \
#	echo 'import os'; \
#	echo "BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://')"; \
#} > celeryconfig.py

ENV CELERY_BROKER_URL amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@$RABBITMQ_HOST
#ENV CELERY_ENABLE_UTC = True
#ENV CELERY_TIMEZONE = "UTC"

#USER myuser

ENTRYPOINT ["/apps/worker/run-celery-worker.sh"]
