FROM node:12.22.1 as build-deps
WORKDIR /app/frontend
COPY package.json /app/frontend
COPY yarn.lock /app/frontend
RUN yarn
COPY . /app/frontend
RUN yarn build

FROM nginx:1.12-alpine
RUN rm /usr/share/nginx/html/index.html
COPY --from=build-deps /app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]