version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: api
    command: gunicorn geocore.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./backend/:/app/api/
    expose:
      - 8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  db:
    image: mdillon/postgis:latest
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

  redis:
    image: redis

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  db-data:

networks:
  front-tier:
  back-tier: