export const GMAP_DRIVER = 'gmap';
export const MAPBOX_DRIVER = 'mapbox';

export const CONFIG_SWITCH_MAP_DRIVER = 'CONFIG_SWITCH_MAP_DRIVER';
export const CONFIG_SET_MAP_VIEWPORT = 'CONFIG_SET_MAP_VIEWPORT';
export const CONFIG_SWITCH_MAP_TYPE = 'CONFIG_SWITCH_MAP_TYPE';
