export const UUT_SAVE_LAYER_BEGIN = 'UUT_SAVE_LAYER_BEGIN';
export const UUT_SAVE_LAYER_SUCCESS = 'UUT_SAVE_LAYER_SUCCESS';
export const UUT_SAVE_LAYER_FAILURE = 'UUT_SAVE_LAYER_FAILURE';
export const UUT_SAVE_LAYER_DISMISS_ERROR = 'UUT_SAVE_LAYER_DISMISS_ERROR';
export const UUT_GET_UUT_LAYERS_BEGIN = 'UUT_GET_UUT_LAYERS_BEGIN';
export const UUT_GET_UUT_LAYERS_SUCCESS = 'UUT_GET_UUT_LAYERS_SUCCESS';
export const UUT_GET_UUT_LAYERS_FAILURE = 'UUT_GET_UUT_LAYERS_FAILURE';
export const UUT_GET_UUT_LAYERS_DISMISS_ERROR = 'UUT_GET_UUT_LAYERS_DISMISS_ERROR';
