"""
Django settings for tileserver project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOG_DIR = os.path.join(BASE_DIR, 'logs')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get('DEBUG', True))

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS').split(' ')

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'gemapocdb'),
        'USER': os.environ.get('DB_USER', 'user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # extensions
    'rest_framework',
    'django_tilestache.apps.DjangoTilestacheConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}

# if DEBUG:
INSTALLED_APPS += [
    'corsheaders'
]

MIDDLEWARE += [
    'corsheaders.middleware.CorsMiddleware'
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# TILESTACHE_FILE_CONF = os.path.join(BASE_DIR, 'conf', 'tilestache', 'tilestache.cfg')
# TILESTACHE_DIRPATH = BASE_DIR
# TILESTACHE_CACHE = {
#     "dirs": "portable",
#     "name": "disk",
#     "gzip": ["txt", "text", "json", "xml", "pbf", "mvt", "geojson"],
#     "path": os.environ.get('TILESTACHE_CACHE_PATH', '/home/navagis/geocore_bucket/tiles'),
#     "umask": "0000"
# }
# TILESTACHE_CACHE = {
#     "class": "TileStache.Goodies.Caches.GoogleCloud:Cache",
#     "kwargs": {
#         "bucket": "geocore-initiative",
#         "access": "GOOGZVWUFK55FKBYGZJU3NI5",
#         "secret": "nP4ai27ZSBaooiUqDvfRnNCLo6VBQMtLg5xYbzXS"
#     }
# }
TILESTACHE_CACHE = {
    "class": "tileserver.GoogleCloudStorageCache:Cache",
    "kwargs": {
        "bucket": "geocore-initiative",
        "access": "GOOGZVWUFK55FKBYGZJU3NI5",
        "secret": "nP4ai27ZSBaooiUqDvfRnNCLo6VBQMtLg5xYbzXS",
        "basedir": "tiles/",
    }
}
# print(TILESTACHE_CACHE)
# TILESTACHE_CACHE = {
#     "name": "Test",
#     "verbose": "True"
# }
# TILESTACHE_CACHE = {
#     "name": os.environ.get('TILESTACHE_CACHE_NAME', 'Redis'),
#     "host": os.environ.get('TILESTACHE_CACHE_HOST', 'geocore-redis'),
#     "port": os.environ.get('TILESTACHE_CACHE_PORT', '6379'),
#     "db": os.environ.get('TILESTACHE_CACHE_DB', '0'),
#     "key prefix": os.environ.get('TILESTACHE_CACHE_KEY_PREFIX', 'geocore')
# }
# TILESTACHE_CACHE = {
#     "name": 'Redis',
#     "host": 'geocore-redis',
#     "port": '6379',
#     "db": 0,
#     "key prefix": 'geocore',
# }


ROOT_URLCONF = 'tileserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 't_jf1qead_154$lr@nw0w^&qizwp33powqxjn*d-h0nfu^01$5')

TIME_ZONE = os.environ.get('TZ', 'Asia/Manila')

USE_I18N = True

USE_L10N = True

USE_TZ = True

WSGI_APPLICATION = 'tileserver.wsgi.application'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
