# Generated by Django 3.0.4 on 2020-04-28 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.Categories')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('csv', 'csv'), ('excel', 'excel'), ('kml', 'kml'), ('kmz', 'kmz'), ('shapefile', 'shapefile'), ('geotiff', 'geotiff'), ('geojson', 'geojson')], max_length=30)),
                ('published_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('A', 'active'), ('I', 'inactive')], max_length=10)),
                ('category_id', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='layers.Categories')),
                ('published_by', models.ForeignKey(blank=True, db_column='published_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'layers',
            },
        ),
    ]
