# Generated by Django 3.0.4 on 2020-04-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
