# Generated by Django 3.0.4 on 2020-04-30 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0002_auto_20200430_0314'),
        ('layers', '0002_auto_20200428_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='layers',
            name='dataset_queue_id',
            field=models.ForeignKey(blank=True, db_column='dataset_queue_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.DatasetQueues'),
        ),
        migrations.AlterField(
            model_name='layers',
            name='type',
            field=models.CharField(blank=True, choices=[('csv', 'csv'), ('excel', 'excel'), ('kml', 'kml'), ('kmz', 'kmz'), ('shapefile', 'shapefile'), ('geotiff', 'geotiff'), ('geojson', 'geojson')], max_length=30, null=True),
        ),
    ]
