# Generated by Django 3.0.4 on 2020-04-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_auto_20200430_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layers',
            old_name='category_id',
            new_name='category',
        ),
    ]
