# Generated by Django 3.0.4 on 2020-04-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_auto_20200430_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layers',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='layers',
            old_name='published_by',
            new_name='publisher',
        ),
    ]
