# Generated by Django 3.0.4 on 2020-05-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_auto_20200430_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layers',
            old_name='dataset_queue_id',
            new_name='dataset_queue',
        ),
    ]
