# Generated by Django 3.0.4 on 2020-05-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0005_datasets_tilestache_layer'),
        ('layers', '0007_auto_20200503_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layers',
            name='dataset_queue',
        ),
        migrations.AddField(
            model_name='layers',
            name='dataset',
            field=models.ForeignKey(blank=True, db_column='dataset_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.Datasets'),
        ),
    ]
