# Generated by Django 3.0.4 on 2021-05-25 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryCountries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(null=True)),
                ('psgc_ph', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'boundaries_countries',
            },
        ),
        migrations.CreateModel(
            name='BoundaryRegions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(null=True)),
                ('reg_code', models.CharField(max_length=20, null=True)),
                ('reg_name', models.CharField(max_length=256, null=True)),
                ('psgc_ph', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('parent', models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='boundaries.BoundaryCountries')),
            ],
            options={
                'db_table': 'boundaries_regions',
            },
        ),
        migrations.CreateModel(
            name='BoundaryProvinces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(null=True)),
                ('reg_code', models.CharField(max_length=20, null=True)),
                ('pro_code', models.CharField(max_length=20, null=True)),
                ('reg_name', models.CharField(max_length=256, null=True)),
                ('pro_name', models.CharField(max_length=256, null=True)),
                ('psgc_ph', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('parent', models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='boundaries.BoundaryRegions')),
            ],
            options={
                'db_table': 'boundaries_provinces',
            },
        ),
        migrations.CreateModel(
            name='BoundaryMunicipalities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(null=True)),
                ('pro_code', models.CharField(max_length=20, null=True)),
                ('mun_code', models.CharField(max_length=20, null=True)),
                ('reg_code', models.CharField(max_length=20, null=True)),
                ('pro_name', models.CharField(max_length=256, null=True)),
                ('reg_name', models.CharField(max_length=256, null=True)),
                ('mun_name', models.CharField(max_length=256, null=True)),
                ('psgc_ph', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('parent', models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='boundaries.BoundaryProvinces')),
            ],
            options={
                'db_table': 'boundaries_municipalities',
            },
        ),
        migrations.CreateModel(
            name='BoundaryBarangays',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField(null=True)),
                ('pro_code', models.CharField(max_length=20, null=True)),
                ('mun_code', models.CharField(max_length=20, null=True)),
                ('reg_code', models.CharField(max_length=20, null=True)),
                ('bgy_code', models.CharField(max_length=20, null=True)),
                ('pro_name', models.CharField(max_length=256, null=True)),
                ('reg_name', models.CharField(max_length=256, null=True)),
                ('mun_name', models.CharField(max_length=256, null=True)),
                ('bgy_name', models.CharField(max_length=256, null=True)),
                ('psgc_ph', models.CharField(max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='boundaries.BoundaryMunicipalities')),
            ],
            options={
                'db_table': 'boundaries_barangays',
            },
        ),
    ]
