# Generated by Django 3.0.4 on 2021-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundarybarangays',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='boundarycountries',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='boundarymunicipalities',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='boundaryprovinces',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='boundaryregions',
            name='objectid',
        ),
        migrations.AddField(
            model_name='boundarybarangays',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='boundarycountries',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='boundarymunicipalities',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='boundaryprovinces',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='boundaryregions',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
